CREATE SEQUENCE HIBERNATE_SEQUENCE AS INTEGER START WITH 100 INCREMENT BY 1;

CREATE TABLE FOOD (
  ID int NOT NULL,
  TYPE varchar(25) NOT NULL,
  DESCRIPTION varchar(150) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE INVITATION (
  ID int NOT NULL,
  INVITATION_CODE varchar(255) NOT NULL,
  MAX_GUESTS int NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE GUEST (
  ID int NOT NULL,
  CEREMONY_ATTENDANCE bit(1) DEFAULT NULL,
  RECEPTION_ATTENDANCE bit(1) DEFAULT NULL,
  DIETARY_COMMENTS varchar(255) DEFAULT NULL,
  DIETARY_CONCERNS bit(1) DEFAULT NULL,
  FIRST_NAME varchar(40) NOT NULL,
  INVITED_PERSON bit(1) DEFAULT NULL,
  LAST_NAME varchar(40) NOT NULL,
  FOOD_ID int DEFAULT NULL,
  INVITE_ID int NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (FOOD_ID) REFERENCES FOOD(ID),
  FOREIGN KEY (INVITE_ID) REFERENCES INVITATION(ID)
);

