INSERT INTO INVITATION VALUES (1,'AAAA',3);

INSERT INTO FOOD VALUES (1,'Chicken','Grilled Chicken');
INSERT INTO FOOD VALUES (2,'Steak','Ribeye Steak');

INSERT INTO GUEST (ID,CEREMONY_ATTENDANCE,RECEPTION_ATTENDANCE,DIETARY_COMMENTS,DIETARY_CONCERNS,FIRST_NAME,INVITED_PERSON,LAST_NAME,FOOD_ID,INVITE_ID)
VALUES (1,0,1,NULL,0,'Hello',1,'World',NULL,1);

INSERT INTO GUEST (ID,CEREMONY_ATTENDANCE,RECEPTION_ATTENDANCE,DIETARY_COMMENTS,DIETARY_CONCERNS,FIRST_NAME,INVITED_PERSON,LAST_NAME,FOOD_ID,INVITE_ID)
VALUES (2,NULL,NULL,NULL,NULL,'World',1,'Hello',NULL,1);